# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

health_runner:
  name: "health-runner"
# Note that sleep health check (E2) is enabled by default
health_checks:
  sleep_healthcheck:
    run_check: true
    runner_name: sleep-health-runner
    image:
      repo: "us-docker.pkg.dev/gce-ai-infra/health-check/health-runner"
      tag: "4.4-latest"
      pull_policy: "Always"
    env:
      DRY_RUN: "true"
      SLEEP_TIME_MINUTES: "10"
      HELM_CHART: "/app/health_checks/sleep_healthcheck"  # Path to Helm chart in container
      HELM_INSTALL_FLAGS: ""
