
steps:
# Read current version
- name: 'alpine'
  entrypoint: sh
  args:
    - -c
    - |
      _VERSION=$(cat deploy/helm/health_runner/version.txt)
      [ -n "$$_VERSION" ] || { echo "ERROR: _VERSION is empty or not set"; exit 1; };
      echo "$$_VERSION"
