# yamllint disable
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gpu-health-runner
  labels:
    app: gpu-health-runner
spec:
  timeZone: America/Los_Angeles
  schedule: "*/15 * * * *"  # run every 15 minutes
  # suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          serviceAccountName: ds-create
          containers:
          - name: gpu-health-runner
            image: us-docker.pkg.dev/gce-ai-infra/health-check/health-runner:topy
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            env:
            - name: SLEEP_TIME_MINUTES
              value: "120"
            - name: YAML_FILE
              value: "gpu_healthcheck.yaml"
            - name: DRY_RUN
              value: "true"
            - name: IMAGE_TAG
              value: "subset"
            - name: R_LEVEL
              value: "2"
            - name: ACCELERATOR_TYPE
              value: "nvidia-h100-mega-80gb"
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ds-create
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ds-create
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io", "batch"]
  resources: ["daemonsets", "serviceaccounts", "clusterrolebindings", "clusterroles", "nodes", "jobs", "services"]
  verbs: ["list", "get", "create", "delete", "watch", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ds-create
  namespace: default
subjects:
- kind: ServiceAccount
  name: ds-create
  namespace: default
roleRef:
  kind: ClusterRole
  name: ds-create
  apiGroup: rbac.authorization.k8s.io