#!/bin/bash
#
#SBATCH --partition=a3mega
#SBATCH --exclusive
#SBATCH --gpus-per-node 8
#SBATCH --nodes 2

HEALTH_VALIDITY_HOURS=24
DRY_RUN=true
NHOSTS=2
nr=8
BANDWIDTH_THRESHOLD=90
START_MESSAGE_SIZE="2G"
END_MESSAGE_SIZE="8G"
USE_FASTRAK="true"
NCCL_FASTRAK_USE_SNAP="1"
NCCL_FASTRAK_ENABLE_CONTROL_CHANNEL="0"
NCCL_FASTRAK_NUM_FLOWS="2"

NODE_NAME=""
JOB_COMPLETION_INDEX=-1
JOB_NAME="nccl-healthcheck-${SHORT_GUID}-${CHECK_TIME_EPOCH_SEC}"
SERVICE_NAME="nccl-headless-svc-${SHORT_GUID}-${CHECK_TIME_EPOCH_SEC}"
INSTANCE_TYPE="a3-megagpu-8g"

# Launch the litgpt script
sbatch nccl_startup.py